"use client";

import { cn } from "@/lib/utils";

interface MessageItemProps {
  role: "user" | "assistant";
  content: string;
}

export const MessageItem = ({ role, content }: MessageItemProps) => {
  const isUser = role === "user";
  
  // Extract the URL from the ![Image](url) format
  const imageMatch = content.match(/!\[.*?\]\((.*?)\)/);
  const imageUrl = imageMatch ? imageMatch[1] : null;

  return (
    <div className={cn("flex w-full px-4 py-2", isUser ? "justify-end" : "justify-start")}>
      <div className={cn(
        "max-w-[85%] sm:max-w-[75%] rounded-2xl px-5 py-3 text-[15px] leading-relaxed",
        isUser ? "bg-[#2f2f2f] text-white" : "bg-transparent text-gray-100"
      )}>
        
        {/* Loading Dots */}
        {!isUser && content === "" && (
          <div className="flex gap-1.5 py-1 items-center h-5">
            <span className="w-2 h-2 bg-gray-500 rounded-full animate-bounce [animation-delay:-0.3s]"></span>
            <span className="w-2 h-2 bg-gray-500 rounded-full animate-bounce [animation-delay:-0.15s]"></span>
            <span className="w-2 h-2 bg-gray-500 rounded-full animate-bounce"></span>
          </div>
        )}

        {/* Improved Image Rendering with Fallback */}
        {imageUrl && (
          <div className="mt-2">
            <img 
              src={imageUrl} 
              alt="Generated by AI" 
              className="rounded-xl w-full max-w-md object-cover shadow-lg"
              onError={(e) => {
                // If the image fails to load, swap it to an error text!
                e.currentTarget.style.display = 'none';
                e.currentTarget.insertAdjacentHTML('afterend', `<div class="text-red-400 text-sm border border-red-500/30 bg-red-500/10 p-3 rounded-lg">❌ Image loaded, but the browser blocked it. Right-click and inspect to see the URL. URL: ${imageUrl.substring(0, 40)}...</div>`);
              }}
            />
          </div>
        )}

        {/* Standard Text Rendering */}
        {!imageUrl && content !== "" && (
          <div className="whitespace-pre-wrap">{content}</div>
        )}

      </div>
    </div>
  );
};
